pgm.write_txt_pgma('./src/readPGM/CrossPadding.txt', pad_cross, size)
# pgm.write_txt_pgma('./src/readPGM/AmplitudeCross.txt', amp, size)
# pgm.write_txt_pgma('./src/readPGM/AmplitudeCrossCentral.txt', amp_c, size)
# pgm.write_txt_pgma('./src/readPGM/AmplitudeCrossNorm.txt', amp_norm, size)
# pgm.write_txt_pgma('./src/readPGM/AmplitudeCrossCentralNorm.txt', amp_c_norm, size)
# pgm.write_txt_pgma('./src/readPGM/PhaseCrossNorm.txt', phase_norm, size)
# pgm.write_txt_pgma('./src/readPGM/PhaseCrossCentralNorm.txt', phase_c_norm, size)

# pgm.write_pgm('./src/readPGM/AmplitudeCrossNorm.pgm', amp_norm, size)
# pgm.write_pgm('./src/readPGM/AmplitudeCrossCentralNorm.pgm', amp_c_norm, size)
# # pgm.write_pgm('./src/readPGM/AmplitudeCrossInverse.pgm', ampi_norm, size)
# # pgm.write_pgm('./src/readPGM/AmplitudeCrossInverse2030.pgm', tranx, size2)
# pgm.write_pgm('./src/readPGM/PhaseCrossNorm.pgm', phase_norm, size)
# pgm.write_pgm('./src/readPGM/PhaseCrossCentralNorm.pgm', phase_c_norm, size)